spring:
  datasource:
    url: jdbc:h2:mem:forohub;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

security:
  jwt:
    secret: "ChangeThisSuperSecretKeyChangeThisSuperSecretKey"
    expiration-ms: 86400000
